version: '3'
services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=cineflix
      - POSTGRES_USER=cineflix
      - POSTGRES_PASSWORD=cineflix
