server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cineflix
    username: cineflix
    password: cineflix

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: cineflix
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/CineflixKeycloak
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/CineflixKeycloak