server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: cineflix
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: https://keycloak-internship.kdev2.esolutions.ro/auth/realms/esolutions
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-internship.kdev2.esolutions.ro/auth/realms/esolutions
  datasource:
    url: jdbc:postgresql://localhost:5433/cineflix
    username: cineflix
    password: cineflix
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
