server:
  port: 8081
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/cineflix}
    username: ${SPRING_DATASOURCE_USERNAME:cineflix}
    password: ${SPRING_DATASOURCE_PASSWORD:cineflix}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: cineflix
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: https://keycloak-internship.kdev2.esolutions.ro/auth/realms/esolutions
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-internship.kdev2.esolutions.ro/auth/realms/esolutions

custom:
  frontend:
    app-url: ${FRONTEND_URL:http://localhost:3000}