spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testingworkshop
    username: testingworkshop
    password: testingworkshop

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true